pipeline {

    agent any 

    tools {
        gradle 'gradle'
    }
    environment {
        DOCKER_REGISTRY='https://pds.stardust:5005'
        NEXUS_CREDENTIALS = credentials('nexus')
        DOCKER_CREDENTIALS = 'dockerRegistry'
        GEOLOCATION_CONTAINER='geolocation'
        KMS_CONTAINER='kms'
        CSPATH_CONTAINER='cspath'
        API_GTW_CONTAINER='apigtw'
    }

    stages {

        stage('Continuous Delivery') {

            stages {

                stage('Fetch from SCM') {

                    steps {
                        checkout scm
                    }

                }

                stage('Build images') {
                    parallel {

                        stage('Build geolocation') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("geolocation") {

                                    sh 'gradle clean build -x test -PrepoUser=$NEXUS_CREDENTIALS_USR -PrepoPassword=$NEXUS_CREDENTIALS_USR'

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${GEOLOCATION_CONTAINER}:latest-staging")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                        stage('Build sc-kms') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-kms") {

                                    sh 'gradle clean build -x test'

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${KMS_CONTAINER}:latest-staging")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                        stage('Build sc-rest-api') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-rest-api") {

                                    sh 'gradle clean build -x test'

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${API_GTW_CONTAINER}:latest-staging")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                        stage('Build sc-consumer-path') {

                            steps {
                                dir("sc-customer-path") {
                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${CSPATH_CONTAINER}:latest-staging")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                    }
                }

                stage('Deploy stack') {
                    steps {
                        dir("devops/staging") {
                            sh '''
                                ansible-playbook -u pds deploy-staging.yml --extra-vars "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
                            '''
                        }
                    }
                }

            }

        }

    }
}