pipeline {
    agent any 

    environment {
        DOCKER_REGISTRY='https://pds.stardust:5005'
        DOCKER_CREDENTIALS = 'dockerRegistry'
        GEOLOCATION_CONTAINER='geolocation'
        KMS_CONTAINER='kms'
        CSPATH_CONTAINER='cspath'
        API_GTW_CONTAINER='apigtw'
    }

    stages {

        stage('Continuous Delivery') {

            stages {

                stage('Fetch from SCM') {

                    steps {
                        checkout scm
                    }

                }

                stage('Build images') {
                    parallel {

                        stage('Build geolocation') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("geolocation") {

                                    sh '''
                                        chmod +x gradlew
                                        ./gradlew clean build
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${GEOLOCATION_CONTAINER}:latest-dev", "--build-arg env=staging .")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                        stage('Build sc-kms') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-kms") {

                                    sh '''
                                        chmod +x gradlew
                                        ./gradlew clean build
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${KMS_CONTAINER}:latest-dev", "--build-arg env=staging .")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                        stage('Build sc-rest-api') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-rest-api") {

                                    sh '''
                                        chmod +x gradlew
                                        ./gradlew clean build
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${API_GTW_CONTAINER}:latest-dev")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                        stage('Build sc-consumer-path') {

                            steps {
                                dir("sc-customer-path") {
                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${CSPATH_CONTAINER}:latest-dev")
                                            img.push()
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                    }
                }

                stage('Deploy stack') {
                    steps {
                        dir("devops/staging") {
                            sh '''
                                ansible-playbook -u pds deploy-staging.yml
                            '''
                        }
                    }
                }

            }

            post {
                always {
                    cleanWs()
                }
            }

        }

    }
}