pipeline {

    agent any

    tools {
        gradle 'gradle'
    }

    environment {
        DOCKER_REGISTRY='https://pds.stardust:5005'
        NEXUS_CREDENTIALS = credentials('nexus')
        DOCKER_CREDENTIALS = 'dockerRegistry'
        GEOLOCATION_CONTAINER='geolocation'
        KMS_CONTAINER='kms'
        CSPATH_CONTAINER='cspath'
        SENSOR_CONTAINER='sensor'
        FREQUENTATION_CONTAINER='frequentation'
        API_GTW_CONTAINER='apigtw'
    }    

    stages {

        stage('Continuous Delivery') {

            stages {

                stage('Fetch from SCM') {

                    steps {
                        checkout scm
                    }

                }

                stage('Build images') {
                    parallel {

                        stage('Build geolocation') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("geolocation") {

                                    sh '''
                                        gradle confirmReleaseVersion -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${RELEASE_VERSION} -PrepoUser=$NEXUS_CREDENTIALS_USR -PrepoPassword=$NEXUS_CREDENTIALS_USR
                                        gradle build -x test -PrepoUser=$NEXUS_CREDENTIALS_USR -PrepoPassword=$NEXUS_CREDENTIALS_USR
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${GEOLOCATION_CONTAINER}:latest-prod")
                                            img.push()
                                            img.push("${RELEASE_VERSION}")
                                            sh "docker rmi ${img.id}"
                                        }
                                    }

                                    sh '''
                                        gradle updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=${NEXT_SNAPSHOT} -PrepoUser=$NEXUS_CREDENTIALS_USR -PrepoPassword=$NEXUS_CREDENTIALS_USR
                                    '''

                                }
                            }
                        }

                        stage('Build sensor') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-sensor-interaction") {

                                    sh '''
                                        gradle confirmReleaseVersion -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${RELEASE_VERSION}
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${SENSOR_CONTAINER}:latest-prod")
                                            img.push()
                                            img.push("${RELEASE_VERSION}")
                                            sh "docker rmi ${img.id}"
                                        }
                                    }

                                    sh '''
                                        gradle updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=${NEXT_SNAPSHOT}
                                    '''

                                }
                            }
                        }

                        stage('Build frequentation') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("frequentation") {

                                    sh '''
                                        gradle confirmReleaseVersion -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${RELEASE_VERSION}
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${FREQUENTATION_CONTAINER}:latest-prod")
                                            img.push()
                                            img.push("${RELEASE_VERSION}")
                                            sh "docker rmi ${img.id}"
                                        }
                                    }

                                    sh '''
                                        gradle updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=${NEXT_SNAPSHOT}
                                    '''

                                }
                            }
                        }

                        stage('Build sc-kms') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-kms") {

                                    sh '''
                                        gradle confirmReleaseVersion -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${RELEASE_VERSION}
                                        gradle build -x test
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${KMS_CONTAINER}:latest-prod")
                                            img.push()
                                            img.push("${RELEASE_VERSION}")

                                            sh "docker rmi ${img.id}"
                                        }
                                    }

                                    sh '''
                                        gradle updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=${NEXT_SNAPSHOT}
                                    '''

                                }
                            }
                        }

                        stage('Build sc-rest-api') {

                            tools {
                                jdk 'java11'
                            }

                            steps {
                                dir("sc-rest-api") {

                                    sh '''
                                        gradle confirmReleaseVersion -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${RELEASE_VERSION}
                                        gradle build -x test
                                    '''

                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${API_GTW_CONTAINER}:latest-prod")
                                            img.push()
                                            img.push("${RELEASE_VERSION}")
                                            sh "docker rmi ${img.id}"
                                        }
                                    }

                                    sh '''
                                        ./gradle updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=${NEXT_SNAPSHOT}
                                    '''

                                }
                            }
                        }

                        stage('Build sc-consumer-path') {

                            steps {
                                dir("sc-customer-path") {
                                    script {
                                        docker.withRegistry("${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS}") {
                                            def img = docker.build("${CSPATH_CONTAINER}:latest-prod")
                                            img.push()
                                            img.push("${RELEASE_VERSION}")
                                            sh "docker rmi ${img.id}"
                                        }
                                    }
                                }
                            }
                        }

                    }
                }

                stage('Tag release') {
                    steps {
                        dir("devops/production") {
                            sh '''
                                git commit -am \"RELEASE VERSION : ${RELEASE_VERSION}\"
                                git push --set-upstream origin master
                                git tag -a \"${RELEASE_VERSION}\" -m \"RELEASE VERSION : ${RELEASE_VERSION}\"
                                git push --tags
                            '''
                        }
                    }
                }

                stage('Deploy stack') {
                    steps {
                        dir("devops/production") {
                            sh '''
                                ansible-playbook -u pds deploy-production.yml --extra-vars "VERSION=${RELEASE_VERSION} JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
                            '''
                        }
                    }
                }

            }

        }

    }

}