pipeline {

    agent any

    tools {
        gradle 'gradle'
    }

    stages {

        stage('Continuous Integration') {

            stages {

                stage('Fetch from SCM') {

                    steps {
                        checkout scm
                    }

                }

                stage('Build') {
                    steps {
                        dir("notificationserver/") {
                            sh 'gradle clean build -x test'
                        }
                    }
                }

                stage('Test') {
                    steps {
                        dir("notificationserver/") {
                            sh 'gradle test'
                        }
                    }
                }
            }

            post {
                always {
                    publishHTML (target : [allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'notificationserver/build/reports/tests/test',
                        reportFiles: 'index.html',
                        reportName: 'Tests report',
                        reportTitles: 'Tests report'])
                }
            }

        }

    }
}